apiVersion: llmcloud.llmcloud.io/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: llmcloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # TODO(user): Add fields here
